### ISSUE TITLE
As a Pryv dev, I need support to clarify/redesign the usage of Supervisor in order to have a clean and working Cache.

### ISSUE THREAD

**Issue by tmodoux** [pryv/lib-java#16]
As a dev, I need support to clarify/redesign the usage of Supervisor in order to have a clean and working Cache.

**Comment by kebetsi** [comment]
do you mean to implement the correct usage of this: https://github.com/pryv/lib-java/blob/refactor/cross-modules/commons/src/main/java/com/pryv/model/Event.java#L71?

**Comment by tmodoux** [comment]
Yes, first I need to be sure to understand well why and how we use this, to be able to then improve it (I remember a talk, we were speaking about improving this feature)

**Comment by kebetsi** [comment]
the aim of the Supervisor is to ensure that a single instance of any Event is used. It's a facilitator for 3P devs.
