### ISSUE TITLE
As a Pryv dev, I need to refactor Event class

### ISSUE THREAD

**Issue by kebetsi** [pryv/lib-java#19]
## Test-first refactoring:
1. Event.java + its unit tests  
2. dependent classes in lib-java  
3. its dependent tests  
(repeat 2 & 3)  
4. dependent repositories  
5. their tests  
(repeat 4 & 5)

**Comment by tmodoux** [comment]
Remaining:
- Validate clientId removal
- Validate ID generation
- Validate Supervisor refactoring
- Improve CUID
