### ISSUE TITLE
As a 3P dev, I need to be able to use the lib without the duplicate file error during apk assembling

### ISSUE THREAD

**Issue by kebetsi** [pryv/lib-java#29]
instead of using packagingOptions.exclude or .filterFirst

**Comment by kebetsi** [comment]
@tmodoux If it is linked to the cross-compilation feature, can you close this issue?

**Comment by tmodoux** [comment]
I think the library split resolved this issue since the gradle quick fix was commented out in the same time... I will check it tomorrow and close the issue if ok.
